# Generated by Django 2.1.1 on 2019-06-26 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drivingtest.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('text', models.TextField(default='text')),
                ('text_en', models.TextField(default='text', null=True)),
                ('text_hi', models.TextField(default='text', null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=drivingtest.models.Option_image)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('question_en', models.TextField(max_length=1000, null=True)),
                ('question_hi', models.TextField(max_length=1000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=drivingtest.models.Question_image)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=True)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingtest.Question'),
        ),
    ]
